-- Migration number: 0002 	 2025-10-24T20:13:26.594Z
DROP TABLE IF EXISTS Progress;
CREATE TABLE IF NOT EXISTS Progress (Id INTEGER, UserId TEXT, LessonId INTEGER, Type TEXT, Score INTEGER, Total INTEGER,  Timestamp TEXT, Synced INTEGER);